/*
 * Constantes / ActionTypes
 */

export const productsActionTypes = {
  GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
  SET_PRODUCT_DETAIL: 'SET_PRODUCT_DETAIL',
  TOGGLE_SEARCH: 'TOGGLE_SEARCH',
  CLOSE_SEARCH: 'CLOSE_SEARCH',
  OPEN_SEARCH: 'OPEN_SEARCH',
  GET_SEARCH_STATUS: 'GET_SEARCH_STATUS',
  // ADD_ITEM: 'ADD_ITEM',
  // DELETE_ITEM: 'DELETE_TODO', // OPCIONAL
};
